---
- hosts: photo_upload
  vars:
    - os_packages:
      - git
    - python_packages:
      - boto3
  tasks:
    - name: "install git"
      yum: name=git state=latest
      become: yes
    - name: "sychronize repository"
      git: repo=https://github.com/korsakm/awss.git dest=~/photo_upload
    - file: path=~/.aws state=directory
    - copy: src=aws.config dest=~/.aws/config
